[versions]
annotation = "1.10.0"
androidannotationsApi = "4.8.0"
appcompat = "1.7.1"
eventbus = "3.3.1"
legacySupportV4 = "1.0.0"
preference = "1.2.1"
timber = "5.0.1"


[libraries]
androidannotationsApi = { module = "org.androidannotations:androidannotations-api", version.ref = "androidannotationsApi" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
legacySupportV4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
