plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ms_square.android.design.overlay'
    compileSdk project.ANDROID_BUILD_SDK_VERSION

    defaultConfig {
        applicationId "com.ms_square.android.design.overlay"
        minSdk project.ANDROID_BUILD_MIN_SDK_VERSION
        targetSdk project.ANDROID_BUILD_TARGET_SDK_VERSION
        versionCode 5
        versionName "1.0.4"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                    "resourcePackageName": "com.ms_square.android.design.overlay",
                    "androidManifestFile": "$projectDir/src/main/AndroidManifest.xml"
                ]
            }
        }
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        debug {
            buildConfigField "String", "BUILD_NUMBER", "\"debug\""
            minifyEnabled false
        }
        release {
            buildConfigField "String", "BUILD_NUMBER", "\"release\""
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // Support libraries migrated to AndroidX
    implementation "androidx.legacy:legacy-support-v4:1.0.0"
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "androidx.annotation:annotation:1.10.0"

    // Android Annotations Library
    implementation "org.androidannotations:androidannotations-api:${project.androidAnnotationsVersion}"
    annotationProcessor "org.androidannotations:androidannotations:${project.androidAnnotationsVersion}"

    // EventBus
    implementation "org.greenrobot:eventbus:${project.eventBusVersion}"

    // Timber for logging
    implementation "com.jakewharton.timber:timber:${project.timberVersion}"

    // Color Picker Preference
    implementation project(':ColorPickerPreference')

    // Android Utility Library
    // implementation "com.ms-square:android-util:${project.androidUtilVersion}"
}
